### ISSUE TITLE
Bounty: Unpaid Issue

### ISSUE THREAD

**Issue by RaghavAggarwal1** [RaghavAggarwal1/GeoTrajectoryHub-Geospatial-Trajectory-Visualization-Query-System#2]
### Reward Size in USD
0 USD

## Bounty

The Project has a complete working front end and backend. But its Missing the API to connect the front end to the backend. The front end is completely written in React.js and deck.gl while the backend is made using Scala and Spark. The api will transfer information from the file uploaded in the front end by the user to be read by the backend. Right now the backend is just reading from the sample file and creating general data. The API will also call one of the 3 functions and displaying their results. 

## Acceptance Criteria

The API can do following -
1. Successfully upload the user file for data to be transmitted to backend.
2. Successfully pass data to desired 1/3 functions and display information returned from the desired function.

Go to [Mintycode](https://mintycode.io/raghavaggarwal1/GeoTrajectoryHub-Geospatial-Trajectory-Visualization-Query-System?action=CREATOR_OFFERING_MODAL&offeringId=d9b508fe-2ffd-4c6b-9614-f136c3582e39&owner=raghavaggarwal1&name=GeoTrajectoryHub-Geospatial-Trajectory-Visualization-Query-System&type=BOUNTIES) to approve the Bounty.

    
[![mintycode](https://imageupload.io/ib/LvxMwrPxam1JW9e_1693210482.png)](https://mintycode.io)

**Comment by HkSolDev** [comment]
The Reward is of 0 dollar how  its a bounty
